version: "3.9"
    
services:
    db:
        image: mysql
        volumes:
            - ./database:/var/lib/mysql
        ports:
            - 3306:3306
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: peximob
            MYSQL_DATABASE: imob
            MYSQL_USER: peximob
            MYSQL_PASSWORD: peximob
